In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv('insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
x= df.drop(columns=['charges'])
y= df['charges']

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.2, random_state=42)

In [6]:
from sklearn.preprocessing import OneHotEncoder

In [7]:
# Identify categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns

# Initialize the OneHotEncoder
ohe = OneHotEncoder(sparse_output=False, drop='first')

# Fit and transform the categorical columns
encoded_data = ohe.fit_transform(df[categorical_cols])

# Get the names of the encoded features
encoded_features = ohe.get_feature_names_out(categorical_cols)

# Create a DataFrame with the new encoded features
encoded_df = pd.DataFrame(encoded_data, columns=encoded_features, index=df.index)

# Drop the original categorical columns from the original DataFrame
df_numeric = df.drop(columns=categorical_cols)

# Concatenate the numeric and encoded DataFrames
df_final = pd.concat([df_numeric, encoded_df], axis=1)

C:\Users\Mazhar Iqbal\AppData\Local\Temp\ipykernel_9956\3618922668.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=['object']).columns

In [8]:
df_final.head()

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,0.0,1.0,0.0,0.0,1.0
1,18,33.770,1,1725.55230,1.0,0.0,0.0,1.0,0.0
2,28,33.000,3,4449.46200,1.0,0.0,0.0,1.0,0.0
3,33,22.705,0,21984.47061,1.0,0.0,1.0,0.0,0.0
4,32,28.880,0,3866.85520,1.0,0.0,1.0,0.0,0.0

In [9]:
from sklearn.linear_model import LinearRegression

model= LinearRegression()
model.fit(x_train,y_train)

ValueError: could not convert string to float: 'female'

In [10]:
y_pred = model.predict(x_test)

In [13]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print("R-squared:", r2)

n = x_test.shape[0]
p = x_test.shape[1]

adjusted_r2 = 1 - ((1-r2) * (n-1) / (n-p-1))
print("Adjusted R-squared:", adjusted_r2)

R-squared: 1.0
Adjusted R-squared: 1.0

In [ ]:
import pa