**Pandas**

In [2]:
import pandas as pd

df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=["A","B","C"],index=["x","y","z"])

In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.3.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mazhar iqbal\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mazhar iqbal\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\mazhar iqbal\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.2-cp313-cp313-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 1.0 MB/s eta 0:00:11
   - -------------------------------------- 0.5/11.0 MB 1.0 MB/s eta 0:00:11
   -- ------------------------------------- 0.8/11.0 MB 1.1 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/11.0 MB 1.1 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/11.0 MB 1.0 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/11.0 MB 1.0 MB/s eta 0:00:10
   ----- ---------------------------------- 1.6/11.0 MB 991.5 kB/s eta 0:00:10
   ------ --------------------------------- 1.8/11.0 MB 1.0 MB/s eta 0:00:09
   ------- -------------------------------- 2.1/11.0 MB 1.1 MB/s eta 0:00:09
   -------- ------------------------------- 2.4/11.0 MB 1.1 MB/s eta 0:00:09
   --------- ------------------------------ 2.6/11.0 MB 1.1 MB/s eta 0:00:08
   ---------- ----------------------------- 2.9/11.0 MB 1.1 MB/s eta 0:00:08
   ----------- ---------------------------- 3.1/11.0 MB 1.1 MB/s eta 0:00:08
   ------------ --------------------------- 3.4/11.0 MB 1.1 MB/s eta 0:00:07
   ------------- -------------------------- 3.7/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 3.9/11.0 MB 1.1 MB/s eta 0:00:07
   --------------- ------------------------ 4.2/11.0 MB 1.1 MB/s eta 0:00:07
   ---------------- ----------------------- 4.5/11.0 MB 1.1 MB/s eta 0:00:06
   ----------------- ---------------------- 4.7/11.0 MB 1.1 MB/s eta 0:00:06
   ----------------- ---------------------- 4.7/11.0 MB 1.1 MB/s eta 0:00:06
   ------------------- -------------------- 5.2/11.0 MB 1.1 MB/s eta 0:00:06
   -------------------- ------------------- 5.5/11.0 MB 1.1 MB/s eta 0:00:05
   --------------------- ------------------ 5.8/11.0 MB 1.1 MB/s eta 0:00:05
   --------------------- ------------------ 6.0/11.0 MB 1.1 MB/s eta 0:00:05
   ---------------------- ----------------- 6.3/11.0 MB 1.1 MB/s eta 0:00:05
   ----------------------- ---------------- 6.6/11.0 MB 1.1 MB/s eta 0:00:04
   ------------------------ --------------- 6.8/11.0 MB 1.1 MB/s eta 0:00:04
   ------------------------- -------------- 7.1/11.0 MB 1.1 MB/s eta 0:00:04
   -------------------------- ------------- 7.3/11.0 MB 1.1 MB/s eta 0:00:04
   --------------------------- ------------ 7.6/11.0 MB 1.2 MB/s eta 0:00:03
   ---------------------------- ----------- 7.9/11.0 MB 1.1 MB/s eta 0:00:03
   ----------------------------- ---------- 8.1/11.0 MB 1.2 MB/s eta 0:00:03
   ----------------------------- ---------- 8.1/11.0 MB 1.2 MB/s eta 0:00:03
   ------------------------------ --------- 8.4/11.0 MB 1.1 MB/s eta 0:00:03
   ------------------------------- -------- 8.7/11.0 MB 1.1 MB/s eta 0:00:03
   ------------------------------- -------- 8.7/11.0 MB 1.1 MB/s eta 0:00:03
   ------------------------------- -------- 8.7/11.0 MB 1.1 MB/s eta 0:00:03
   -------------------------------- ------- 8.9/11.0 MB 1.1 MB/s eta 0:00:02
   -------------------------------- ------- 8.9/11.0 MB 1.1 MB/s eta 0:00:02
   --------------------------------- ------ 9.2/11.0 MB 1.0 MB/s eta 0:00:02
   --------------------------------- ------ 9.2/11.0 MB 1.0 MB/s eta 0:00:02
   ---------------------------------- ----- 9.4/11.0 MB 1.0 MB/s eta 0:00:02
   ---------------------------------- ----- 9.4/11.0 MB 1.0 MB/s eta 0:00:02
   ---------------------------------- ----- 9.4/11.0 MB 1.0 MB/s eta 0:00:02
   ----------------------------------- ---- 9.7/11.0 MB 983.8 kB/s eta 0:00:02
   ----------------------------------- ---- 9.7/11.0 MB 983.8 kB/s eta 0:00:02
   ----------------------------------- ---- 9.7/11.0 MB 983.8 kB/s eta 0:00:02
   ------------------------------------ --- 10.0/11.0 MB 961.3 kB/s eta 0:00:02
   ------------------------------------- -- 10.2/11.0 MB 950.0 kB/s eta 0:00:01
   ------------------------------------- -- 10.2/11.0 MB 950.0 kB/s eta 0:00:01
   -------------------------------------- - 10.5/11.0 MB 945.1 kB/s eta 0:00:01
   -------------------------------------- - 10.5/11.0 MB 945.1 kB/s eta 0:00:01
   -------------------------------------- - 10.5/11.0 MB 945.1 kB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 916.5 kB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 916.5 kB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 907.3 kB/s  0:00:12
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pandas

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed pandas-2.3.2 pytz-2025.2 tzdata-2025.2

In [3]:
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [5]:
df.head(1)

   A  B  C
0  1  2  3

In [6]:
df.tail(2)

   A  B  C
1  4  5  6
2  7  8  9

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

In [12]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [13]:
df.nunique()

A    3
B    3
C    3
dtype: int64

In [15]:
df.shape

(3, 3)

In [55]:
cofee = pd.read_csv(r'C:\Users\AbdulSattar\OneDrive\Documents\Python\warm up data/cofee.csv')

In [11]:
cofee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [18]:
cofee.sample(5)

         Day Coffee Type  Units Sold
13    Sunday       Latte          35
10  Saturday    Espresso          45
1     Monday       Latte          15
0     Monday    Espresso          25
7   Thursday       Latte          30

In [14]:
cofee.loc[0]  # (r,c)

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [20]:
cofee.loc[[0,1,3]]  # (r,c)

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
3  Tuesday       Latte          20

In [31]:
cofee.loc[0:3,["Day","Coffee Type"]]  # (r,c)

       Day Coffee Type
0   Monday    Espresso
1   Monday       Latte
2  Tuesday    Espresso
3  Tuesday       Latte

In [28]:
cofee.iloc[0:4,:2]

       Day Coffee Type
0   Monday    Espresso
1   Monday       Latte
2  Tuesday    Espresso
3  Tuesday       Latte

In [37]:
cofee.index = cofee.Day

In [38]:
cofee

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25
Thursday    Thursday    Espresso          40
Thursday    Thursday       Latte          30
Friday        Friday    Espresso          45
Friday        Friday       Latte          35
Saturday    Saturday    Espresso          45
Saturday    Saturday       Latte          35
Sunday        Sunday    Espresso          45
Sunday        Sunday       Latte          35

In [40]:
cofee.loc["Monday"]

           Day Coffee Type  Units Sold
Day
Monday  Monday    Espresso          25
Monday  Monday       Latte          15

In [42]:
cofee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [47]:
cofee.iloc[0:3,2]=10

In [48]:
cofee.head()

         Day Coffee Type  Units Sold  (1, 2)
0     Monday    Espresso          10      10
1     Monday       Latte          10      10
2    Tuesday    Espresso          10      10
3    Tuesday       Latte          20      10
4  Wednesday    Espresso          35      10

In [51]:
cofee.iat[2,1]

'Espresso'

In [52]:
cofee["Coffee Type"]

0     Espresso
1        Latte
2     Espresso
3        Latte
4     Espresso
5        Latte
6     Espresso
7        Latte
8     Espresso
9        Latte
10    Espresso
11       Latte
12    Espresso
13       Latte
Name: Coffee Type, dtype: object

In [57]:
cofee.sort_values(["Units Sold","Coffee Type"],ascending=[0,1])

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [58]:
bios = pd.read_csv(r"C:\Users\AbdulSattar\Downloads\bios.csv")

In [59]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25